name: Deploy docs

on:
  push:
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 6 * * 6'

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: oprypin/install-crystal@v1
      - name: Generate API docs
        run: |
          crystal docs --project-name=crystal-chipmunk --project-version='' --source-refname=master src/chipmunk.cr &&
          cp .github/redirect.html docs/index.html
      - name: Deploy to gh-pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: oprypin/push-to-gh-pages@v3
        with:
          publish_dir: docs
          commit_message: 'Generate API documentation: '
